sudo: required
dist: bionic
arch:
  - amd64
  - ppc64le

language: python
python:
  - "3.6"
  - "3.7"
  
jobs:
  include:
    - python: '3.8' # this is not strictly necessary
      env: EXTRA_TESTS=true
    - python: '3.7'
      env: EXTRA_TESTS=true
      
script: 
  - python --version
  - echo $EXTRA_TESTS
